### ISSUE TITLE
Support: override layout?

### ISSUE THREAD

**Issue by TheEmpty** [jwilm/koa-hbs#29]
I was looking through the code and didn't see a way to overwrite the layout for a render. Am I right about that? My problem is that my root page has a different layout (or no layout) than the rest of my pages. I was expecting something like

```javascript
this.render('hero-page', {
  title: "Our Product",
  template: null
});
```

**Comment by jwilm** [comment]
You can specify `{{!< layoutName }}` somewhere in your template _hero-page_ to override the default layout. Maybe you can add a layout named _empty_ which only has `{{{body}}}` in it for the blank pages.

**Comment by TheEmpty** [comment]
Thanks :)

**Comment by mzgol** [comment]
I had this issue as well. The empty template hack is a nice one but IMO it'd be more intuitive to have it built-in.
