### ISSUE TITLE
Docker + Digital Ocean

### ISSUE THREAD

**Issue by TheEmpty** [jwilm/koa-hbs#31]
Just wanted to let you know, I had to downgrade my `koa-hbs` from `0.7.0` to `0.6.0`. On Dokku via Digital Ocean, `this.render` would never respond in `0.7.0`. Wasn't able to fully diagnose it.

**Comment by jwilm** [comment]
Thanks for the report. What version of koa/node were you on?

**Comment by TheEmpty** [comment]
Koa: ^0.14.0
Node: v0.12.0-linux-x64

Note: do also have router after HBS.

**Comment by TheEmpty** [comment]
Okay, so it was because Mongoose was at `^4.0.0` because of one of our dev machines. The page I was testing on was a static page, so I'm still not sure why the render never returned. I am using koa-sessions though, so I assume that must be hitting the database and having some issues. So seems it's downstream from render and not an issue of koa-hbs.
