### ISSUE TITLE
Nested partials aren't respected the first time

### ISSUE THREAD

**Issue by mzgol** [jwilm/koa-hbs#32]
I have a layout like:
```html
<!DOCTYPE html>
<html>
<head>
  <title>Example title</title>
</head>
<body>
  <div id="sidebar">
    {{# block "sidebar" }}
      <!-- sidebar goes here -->
    {{/ block }}
  </div>
  {{{body}}}
</body>
</html>
```
with two partials, one in `partials/sidebar.hbs`:
```html
{{# contentFor "sidebar" }}
    <nav>
        <ul class="sidebar-submenu">
            {{# block "sidebar-submenu" }}
                <!-- sidebar-submenu goes here -->
            {{/ block }}
        </ul>
    </nav>
</div>
{{/ contentFor }}
```
and one in `partials/sidebar-submenu/submenu-item.hbs` with contents:
```html
{{> sidebar }}

{{# contentFor "sidebar-submenu" }}
    <li>List elem 1</li>
    <li>List elem 2</li>
{{/ contentFor }}
```
I then include this partial in one of the templates:
```html
{{> sidebar-submenu/submenu-item }}

<div>The actual content</div>
```
The end result is that the first time someone visits the relevant page, the `sidebar` partial gets populated but the `sidebar-submenu` one doesn't (I still see the `<!-- sidebar-submenu goes here -->` comment instead of the content). After the second refresh it's all fine.

Restarting the server doesn't help.

koa 0.20.0, koa-hbs 0.7.0

**Comment by jwilm** [comment]
Hey! Sorry it took me so long to get to this. I'm looking into it right now.

**Comment by jwilm** [comment]
There appears to be an ordering issue with `contentFor` and `block`. Until that's fixed, the workaround is to make sure `contentFor` appears before the corresponding `block`. In your example, this amounts to the following change.

```diff
diff --git a/partials/sidebar-submenu/submenu-item.hbs b/partials/sidebar-submenu/submenu-item.hbs
index 08a7587..f8cb59e 100644
--- a/partials/sidebar-submenu/submenu-item.hbs
+++ b/partials/sidebar-submenu/submenu-item.hbs
@@ -1,6 +1,6 @@
-{{> sidebar }}
-
 {{# contentFor "sidebar-submenu" }}
     <li>List elem 1</li>
     <li>List elem 2</li>
 {{/ contentFor }}
+
+{{> sidebar }}
```

**Comment by jwilm** [comment]
There's no way around the ordering requirement while implementing the `block` and `contentFor` blocks as helpers. They are just executed one after another during template generation. It appears that since handlebars 3 (this project is on 2), there are public APIs for viewing/modifying the AST before template generation. `block` and `contentFor` could be reimplemented using that, but that solution is a lot heavier than just using helpers.

I'm going to close this as `wontfix` since there is a pretty non-invasive workaround.
