### ISSUE TITLE
 the viewPath maybe an array

### ISSUE THREAD

**Issue by tonylinyy** [jwilm/koa-hbs#36]
the doc says:
viewPath: [required] Full path from which to load templates (Array|String)
when I set an array,it goes wrong:
TypeError: Path must be a string,
is it possible the viewPath an array,just like viewPath: ['./client/web','./client/web2'],

**Comment by jwilm** [comment]
It was intended to support a list of paths. This may be a bug. I'll see if I can get a repro going over here. Thanks!

**Comment by jwilm** [comment]
@tonylinyy I was able to reproduce your issue. Can you check that the referenced commit covers your use case?
